-- Users table for OPR Portal
-- Roles: owner, admin, staff
-- Stores only password hashes (BCrypt/Argon2 recommended). No plaintext passwords.

CREATE TABLE IF NOT EXISTS `users` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`password_hash` VARCHAR(255) NOT NULL,
	`role` ENUM('owner','admin','staff') NOT NULL DEFAULT 'admin',
	`is_active` TINYINT(1) NOT NULL DEFAULT 1,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	UNIQUE KEY `uq_users_name` (`name`),
	KEY `idx_users_role` (`role`),
	KEY `idx_users_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Optional: seed an initial owner account. Replace the hash with one generated by PHP password_hash().
-- Example to generate: <?php echo password_hash('changeme', PASSWORD_DEFAULT); ?>
-- INSERT INTO `users` (`name`, `password_hash`, `role`, `is_active`)
-- VALUES ('Owner', '$2y$10$REPLACE_WITH_PASSWORD_HASH...............................................', 'owner', 1);


